name: msdo-main-pipeline

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: 'main' # Will need changing to Develop
    secrets:
      GH_TOKEN:
        required: false

jobs:
  # Uncomment once template-scanning is needed
  # msdo-dynamic-scanning:
  #   uses: ./.github/workflows/MSDO-dynamic-scanning.yml
  #   permissions:
  #     contents: read
  #     id-token: write
  #     actions: read
  #     security-events: write
  #   with:
  #     branch: ${{ inputs.branch }}
  #   secrets:
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  secret-scan-credscan:
    uses: ./.github/workflows/MSDO-credscan.yml
    with:
      branch: ${{ inputs.branch }}
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    #needs: msdo-dynamic-scanning Uncomment once template-scanning is needed
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  secret-scan-trufflehog:
    uses: ./.github/workflows/MSDO-trufflehog.yml
    with:
      branch: ${{ inputs.branch }}
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-credscan
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  secret-scan-gitleaks:
    uses: ./.github/workflows/MSDO-gitleaks.yml
    with:
      branch: ${{ inputs.branch }}
    permissions:
      contents: read
      id-token: write
      actions: read
      security-events: write
    needs: secret-scan-credscan
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
